### ISSUE TITLE
add support for edit and delete operations

### ISSUE THREAD

**Issue by shay123g** [mini-services/miniurl#106]
DELETE /url/:id for delete
PUT/PATCH /url/:id for edit

**Comment by Danielg212** [comment]
@shay123g  I'll take it oke?

**Comment by shay123g** [comment]
Go ahead

**Comment by Danielg212** [comment]
PR is open here https://github.com/mini-services/miniurl/issues/106

**Comment by SnirShechter** [comment]
Closed in #191
