### ISSUE TITLE
Helm upgrade doesn't work when deploying a Postgres

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#107]
*Background*
When deploying MiniUrl via a helm chart and the storage.deploy option set to true, we're also deploying a Postgres subchart with it. The subchart auto-generates the credentials in a Kubernetes secret.

*Problem*
When upgrading the helm chart (that is, running `helm upgrade` in a Kubernetes cluster that already has the helm chart installed), the Postgres subchart won't upgrade since it requires the existing Postgres password.

*Solution*
Fix the helm chart. This should fix it:
https://stackoverflow.com/a/64325744

Also, consider moving the Postgres credentials from the Postgres-created secret to our own secret, if it makes sense.

**Comment by saharhagbi** [comment]
I will take it
