### ISSUE TITLE
Add README tags

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#111]
* Slack (not sure where to get it, but it's not in the link)
* (build) build github workflow, test github workflow (You'll need to rename the workflows on .github/workflows to make it work)
* CI/CD (build: passing, tests: passing)
* (license) License
* (issue-tracking) issues
* (code coverage) codecov
* (analysis & code coverage) Code climate (open an issue to integrate https://codeclimate.com/ and add their shield after it's integrated)
* (analysis) Snyk
* (downloads) Docker
* (size) Docker
* (downloads) Helm (open a separate issue to do this once we deploy it to Helmhub)
* (version) helm (open a separate issue to do this once we deploy it to Helmhub)
* (version) docker image
* (activity) Github last commit
* (platform-support) node 14.8+

**Comment by yehuda-kahan** [comment]
I'm working in it
