### ISSUE TITLE
Change the url_info table type to UrlInformation

### ISSUE THREAD

**Issue by Danielg212** [mini-services/miniurl#115]
change the model in `InMemory` to return UrlWithInformation by the following type:

```typescript
interface Url {
    id: string
    // ...
}
interface UrlInformation {
    ip: string
    // ...
}
type UrlWithInformation = Url & UrlInformation
```

Also, add the request host to url_info table

**Comment by SnirShechter** [comment]
Also, remove UrlRequestData (replace with UrlWithInformation).

**Comment by Danielg212** [comment]
@Yardenb can we close this one?

**Comment by Yardenb** [comment]
@Danielg212 Yes, it was merged today.
