### ISSUE TITLE
Redis: check functionality edit and delete operations after issue #106 is done

### ISSUE THREAD

**Issue by shay123g** [mini-services/miniurl#127]
check functionality of edit and delete operations.
how to achieve this?
first install Redis DB locally on your computer\VM. 
for minimum setup you can install over docker - https://hub.docker.com/_/redis

after you start the DB instance save url record in the db using rest api tool such postman, follow our README.md for further instructions. alternatively you can save url using redis-cli

then just call the relevant API's

**Comment by veronica-sherman** [comment]
Hi, I'd like to work on this item please.

**Comment by shay123g** [comment]
> Hi, I'd like to work on this item please.

Go ahead😃
