### ISSUE TITLE
Make the database updates more performant

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#15]
### Problem
The database is being accessed many times, which slows down the database and server quite heavily.

### Solution
Make a list of all the non-live updates - incVisitCount, incInfoCount etc.

Design an asynchronous batch updating functionality for the frequent non-live updates. e.g incInfoCount should keep an in-memory count inside the driver and flush them all every 5-10 seconds.

**NOTE** Before the design, check if there's a better way to handle it in the connector libraries (e.g `Knex`) instead of implementing our own.

## EDIT
After checking, there's no such functionality in Knex. The `PostgresStorageDriver` should implement a batch-update mechanism for incInfoCount and incVisitCount. each of these should save its own cache and flush it every 10 seconds. Their usage in routes should also be non-blocking.

**Comment by Man-RP** [comment]
I'll do this
