### ISSUE TITLE
Url cleanup upgrades

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#16]
* Use "last used" instead of "created at"

**Comment by shay123g** [comment]
@SnirShechter

**Comment by shay123g** [comment]
meeting summary:
data structure:
```javascript
export interface StoredUrl {
	id: string
	url: string
	createdAt: string
	updatedAt: string
	active:boolean
}
export interface UrlInformation extends StoredUrl {
	urlVisitCount: number
	infoVisitCount: number
	updates: string
	ip: string
	region: string
	mobile: boolean
}
```
- expiration time will be measure from **url creation time**

need to decide:

- [ expiration time values  ]
- [control for each site \ globally in config]

full discussion can be found [here](https://app.slack.com/client/T01HN0XEVMZ/C01MQ6Q3YSK/details/info)

**Comment by Danielg212** [comment]
Hi @shay123g, 
I did changes so the current state:


```javascript
export interface StoredUrl {
	id: string
	url: string
	createdAt: string
	updatedAt: string
}

export interface UrlInformation extends StoredUrl {
	ip: string
	urlVisitCount: number
	infoVisitCount: number
	region: string
	mobile: boolean
	lastUse: string
}
```

**Comment by shay123g** [comment]
@Danielg212 
10x

pls update me when dev (release branch) is updated with ur code
