### ISSUE TITLE
Error during npm start/run dev

### ISSUE THREAD

**Issue by BattleOfPlassey** [mini-services/miniurl#173]
I face below error during npm start or npm run dev

(node:10656) ExperimentalWarning: The ESM module loader is experimental.
(node:10656) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at link (internal/modules/esm/module_job.js:41:21)

**Comment by Yardenb** [comment]
Hey @BattleOfPlassey, what version of node do you have installed on your computer?

**Comment by BattleOfPlassey** [comment]
> Hey @BattleOfPlassey, what version of node do you have installed on your computer?

Oh my bad, i missed the node requirement. Anyway i update my node version and voila it worked !! 

What is the base URL which i should hit on, all i am getting is ROUTE NOT FOUND error

**Comment by Yardenb** [comment]
The base URL can be modified, so it depends on what you are trying to do.
Are you just trying to run it in development mode? If so, please join the slack group, it will be easier and more appropriate to it from there. If that's not the case, please share the errors and the way you are sending the requests.

There is a link to the slack group in the docs section. You can also send me a private message and I'll try to help as best as I can.
