### ISSUE TITLE
Graceful shutdown doesn't work properly

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#2]
We need to implement a "graceful shutdown" upon receiving 'SIGINT', 'SIGTERM'
Our project also running docker. Unfortunately, sending these signals doesn't automatically translate the signals to a graceful shutdown of the running docker.

The solution to this problem is explained here:
[https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/](https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/)
Also, make sure our docker file follows the best practices mentioned in the article.

Relevant files:
src/index.js

you can also search for the comment "// Graceful shutdown" that will take you to the relevant location in the projects' folder

**Comment by veronica-sherman** [comment]
I will take that please.
