### ISSUE TITLE
Graphic design - logo

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#43]

**Comment by ngeshlew** [comment]
@SnirShechter I can take a stab at it if you are interested. Please let me know.

**Comment by SnirShechter** [comment]
Sure, that'd be great!

This project is getting more and more attention and we really need a logo 🙂

**Comment by ngeshlew** [comment]
Great! I'd like more info on this logo design project. If you can answer these few questions, I can get it done ASAP.

### Starter questions
1. What are the different names for your project? Which one do you want in your design?
2. Does the project have a slogan or tagline?
3. What do you like or dislike about your competitor’s branding? Do you have an idea in mind?
4. Which font best fits your brand? Are you looking for a Serif, Sans Serif, Calligraphy, or Display Font?
5. Which colors best suit your brand?

### The most important question
Which logos resonate with you (especially for this project)?

**Comment by SnirShechter** [comment]
@ngeshlew 
Sorry for the late answer.

Honestly, the project is still in early stages so I'm not sure if I'll get all the answers right, but I'll try my best:
- The project name is **MiniUrl**. It's derived from its parent project - MiniServices (probably to be named Minis as in a plural of Mini). This means that MiniUrl is a Mini (other future Minis will follow) of URLs. Also, if you have a better name, you're welcome to suggest it.
- No slogan or taglines yet, but you're welcome to suggest one.
- So we don't have competitors per se (and most other projects that attempt the same are pretty lousy), but [bit.ly](https://bit.ly) have a nice slogan - short URLs, big results. We give that functionality, but our focus is making generic microservices that require zero code and give great results, and MiniUrl is just one of those, which focuses on Url functionality.
- I guess it's either Display or Sans Serif, but certainly not Serif. It should be young, simple and fresh.
- Following the last note, young, fresh, simple colors are probably somewhat light variants of blue/green/purple etc. [This is a good example of colors](https://image.freepik.com/free-vector/gradient-technology-blue-logo-collection_23-2148229323.jpg).
- I was thinking of making a logo which has some generic part (say, color or shape) for the main project (MiniServices) and every Mini (such as this one - MiniUrl) would change it just a bit to its own focus. E.g [this is flexible](https://i.pinimg.com/originals/3d/22/f5/3d22f52b377520118855559ef1308b12.png). The main concept is getting a main pattern for all logos.


I hope I'm being clear enough. Feel free to contact me on the project's Slack too.

**Comment by ngeshlew** [comment]
Thanks @SnirShechter! This is super great! I'll start working on it. You can assign this issue to me.

**Comment by SnirShechter** [comment]
@ngeshlew 

Superb, thanks!

**Comment by SnirShechter** [comment]
@ngeshlew ?
