### ISSUE TITLE
Return generic errors instead of sensitive errors from Storage service

### ISSUE THREAD

**Issue by SnirShechter** [mini-services/miniurl#80]

**Comment by shay123g** [comment]
@SnirShechter

**Comment by SnirShechter** [comment]
@shay123g 

This too, unfortunately, is already taken by Aviad. He didn't yet approve the join request so I didn't assign him.

**Comment by SnirShechter** [comment]
@AviadSofer 
This is what I was talking about as well.

Every function in the storage service (`src/services/storage/index.ts`) should probably change to something like this:
Before:
```
		public async deleteOverdue(timespanMs: number): Promise<number> {
			return this.driver.url.deleteOverdue(timespanMs)
		}
```
After:
```
		public async deleteOverdue(timespanMs: number): Promise<number> {
			try {
    			    return await this.driver.url.deleteOverdue(timespanMs)
			} catch (error) {
			    logger.error(`deleteOverdue failed: ${error}`)
			    throw GeneralError('Could not delete overdue')
		}
```

* I'm not sure if you can just print error or you need error.message or etc.
* GeneralError does not yet exist. You should create a new error inside src/errors/generalError.ts with this content:
```
import createError from 'fastify-error'

export const GeneralError = createError('ERR_GENERAL_ERROR', 'Error', 500)

```
Or something similar.
