### ISSUE TITLE
Rate Limit on creating links, and accessing the server

### ISSUE THREAD

**Issue by lesagi** [mini-services/miniurl#90]

**Comment by shmuelpro** [comment]
Seems like a serious task. can you point out where the potential assignee might look to add the code? 
Might these be two separate issues? 
Is accessing the server from a specific IP address or in general?

**Comment by SnirShechter** [comment]
Hey @shmuelpro, I missed your comment on this issue.

This is a serious task indeed. The purpose is to prevent spam or abuse of the API which is designed to be open to everyone.

It's currently not yet fully designed. If you care to design it (look for examples in other projects, think about the goal product-wise, etc.), I'd very much appreciate it. If you want to talk about it together, pm me on our Slack (there's a link in the README) and we'll schedule a design meeting.

**Comment by shmuelpro** [comment]
Hey @SnirShechter  I am the dude from the facebook group-  pull request. 
you suggested this issue for new guys and I think it needs a little more explanation before solving it

**Comment by SnirShechter** [comment]
It's not for juniors, just for new guys.

The problem is that designing a solution is roughly 70% of the task. We really can't afford doing 70% of all tasks.

Designing this feature is part of the ticket.

**Comment by lesagi** [comment]
Hi,
I'll take this - I'll comment here later this week with a design suggestion/approach
